---
- name: install openvpn to client
  ansible.builtin.apt:
    name: openvpn
    state: present

- name: copy config openvpn to client
  template: 
   src: vpn_c.j2
   dest: /etc/openvpn/openvpn{{tun_num}}.conf
  when: inventory_hostname in groups[clients]

- name: copy config openvpn to server
  template: 
   src: vpn_s.j2
   dest: /etc/openvpn/openvpn{{tun_num}}.conf
  when: inventory_hostname in groups[servers]

- name: Keygen
  ansible.builtin.shell: "openvpn --genkey --secret /etc/openvpn/openvpn{{tun_num}}.key"
  delegate_to: 127.0.0.1

- name: copy key to client
  copy: 
   src: /etc/openvpn/openvpn{{tun_num}}.key
   dest: /etc/openvpn/openvpn{{tun_num}}.key

- name: start openvpn client config 
  ansible.builtin.shell: systemctl start openvpn@openvpn{{tun_num}}
