---
 - name: iptables for client
   template:
     src: iptables-client.j2
     dest: /etc/rc.local
   when: inventory_hostname in groups[clients]

 - name: iptables for server
   template:
     src: iptables-server.j2
     dest: /etc/rc.local
   when: inventory_hostname in groups[servers]

 - name: rc.local run
   ansible.builtin.shell:  /etc/rc.local

