---
- name: Add new host vars
  hosts: '{{ target | default("localhost") }}'
  become:  yes
  tasks:
   - name: "server"
     hosts: all
     vars_prompt:

      - name: "server"
        prompt: "Enter server host"
        private: false

      - name: "client"
        prompt: "Enter client host"
        private: false
   
      - name: "tun_num"
        prompt: "Enter tun number"
        private: false
       
      - name: "ip_srv"
        prompt: "Enter ip remote"
        private: false
       
      - name: "rprt"
        prompt: "Enter rport"
        private: false
   
      - name: "lprt"
        prompt: "Enter lport"
        private: false
   
      - name: "ip_l"
        prompt: "Enter ip local"
        private: false
   
      - name: "ip_r"
        prompt: "Enter ip remote"
        private: false
   
      - name: "type_tcp"
        prompt: "Enter type tcp"
        private: false
