---
- name: Add new host vars
  hosts: '{{ target | default("localhost") }}'
  become:  yes
  vars_prompt:
  - name: "hostspair"
    prompt: "Enter name of hosts-pair file. [name_server+name_client] Example: srv1+hst1"
    private: false
  - name: "server"
    prompt: "Enter server host name (from inventory)"
    private: false
  - name: "client"
    prompt: "Enter client host name (from inventory)"
    private: false
  - name: "tun_num"
    prompt: "Enter tun number"
    private: false
  - name: "ip_srv"
    prompt: "Enter ip remote"
    private: false
  - name: "rprt"
    prompt: "Enter rport"
    private: false
  - name: "lprt"
    prompt: "Enter lport"
    private: false
  - name: "ip_l"
    prompt: "Enter ip local"
    private: false
  - name: "ip_r"
    prompt: "Enter ip remote"
    private: false
  roles:
  - { role: "./roles/new_vars_file" }
     